# Mirrors docker/docker-compose.yml as Terraform-managed resources: one
# Unity Catalog OSS server, one network, two named volumes (metastore db +
# managed table data), and the two host config files bind-mounted
# individually - never the whole conf/ directory, which would clobber the
# image's own baked-in log4j2/hibernate/signing-key files that live
# alongside server.properties (see docker-compose.yml's comments for why).
#
# This is the module that's actually apply-able against the Docker daemon
# on this machine. Don't run it alongside `docker compose up` from
# docker/ at the same time - both bind port 8080 and would conflict.
# docker-compose.yml remains the simpler day-to-day tool; this module
# exists to demonstrate the same topology as Terraform-managed IaC.

terraform {
  required_providers {
    docker = {
      source  = "kreuzwerker/docker"
      version = "~> 3.0"
    }
  }
}

resource "docker_image" "unitycatalog" {
  name         = "unitycatalog/unitycatalog:latest"
  keep_locally = true
}

resource "docker_network" "uc_network" {
  name = "chip_lakehouse_uc_network"
}

resource "docker_volume" "uc_db" {
  name = "chip_lakehouse_unitycatalog_db"
}

resource "docker_volume" "uc_data" {
  name = "chip_lakehouse_unitycatalog_data"
}

resource "docker_container" "uc_server" {
  name  = "chip-lakehouse-unitycatalog"
  image = docker_image.unitycatalog.image_id

  networks_advanced {
    name = docker_network.uc_network.name
  }

  ports {
    internal = 8080
    external = 8080
  }

  # Config files: bind-mounted individually, not the whole directory.
  volumes {
    host_path      = var.server_properties_path
    container_path = "/home/unitycatalog/etc/conf/server.properties"
  }

  # token.txt is generated BY the server on first boot, not supplied by
  # us - if it doesn't exist on the host yet, `touch` it first so Docker
  # has a file to bind-mount rather than creating a directory by mistake.
  volumes {
    host_path      = var.token_file_path
    container_path = "/home/unitycatalog/etc/conf/token.txt"
  }

  # Persistent state: named volumes, not bind mounts.
  volumes {
    volume_name    = docker_volume.uc_db.name
    container_path = "/home/unitycatalog/etc/db"
  }

  volumes {
    volume_name    = docker_volume.uc_data.name
    container_path = "/home/unitycatalog/etc/data"
  }
}
